CREATE TABLE IF NOT EXISTS mansion_buildings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    building_name VARCHAR(255) NOT NULL,
    postal_code VARCHAR(20) NULL,
    prefecture VARCHAR(50) NULL,
    city VARCHAR(100) NULL,
    town VARCHAR(120) NULL,
    address_detail VARCHAR(255) NULL,
    full_address VARCHAR(600) NULL,
    structure VARCHAR(120) NULL,
    floors_above INT NULL,
    floors_below INT NULL,
    built_year_month VARCHAR(20) NULL,
    built_date DATE NULL,
    total_units INT NULL,
    nearest_line VARCHAR(255) NULL,
    nearest_station VARCHAR(120) NULL,
    nearest_access_method VARCHAR(50) NULL,
    nearest_minutes INT NULL,
    transports_json JSON NULL,
    raw_data JSON NULL,
    search_text TEXT NULL,
    source_file VARCHAR(255) NULL,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_mansion_name (building_name),
    INDEX idx_mansion_pref_city (prefecture, city),
    INDEX idx_mansion_station (nearest_station),
    FULLTEXT KEY ft_mansion_search (building_name, full_address, search_text)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
